
name: Application Deployment to AWS Beanstalk

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      targetEnv:
        type: string
        description: Target environment to use for the deployment
        required: true
        default: Development
      applicationtName:
        type: string
        description: AWS Beanstalk application name
        required: true
      version:
        type: string
        description: Version to deploy
        required: true
      packageType:
        type: choice
        description: Package type to deploy
        required: true
        default: jar
        options:
        - jar
        - zip
        - war

permissions:
  id-token: write
  contents: write

env:
  VERSION: ${{ inputs.version }}
  BEANSTALK_APP_NAME: ${{ inputs.applicationName }}
  PACKAGE_TYPE: ${{ inputs.packageType }}
jobs:
  deploy:
    environment: ${{ inputs.targetEnv }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${BEANSTALK_APP_NAME} \
          --source-bundle S3Bucket="cdsolutionsinfo-devops",S3Key="packages/${BEANSTALK_APP_NAME}/${BEANSTALK_APP_NAME}-${VERSION}.${PACKAGE_TYPE}" \
          --version-label "${VERSION}" \
          --description "Deploy ${VERSION} of ${BEANSTALK_APP_NAME}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name  ${BEANSTALK_APP_NAME} --version-label "${VERSION}"
